-- MySQL Script generated by MySQL Workbench
-- Thu Sep  7 08:49:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering



-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema foodpantry
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema foodpantry
-- -----------------------------------------------------

USE `foodpantry` ;

-- -----------------------------------------------------
-- Table `foodpantry`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foodpantry`.`user` ;

CREATE TABLE IF NOT EXISTS `foodpantry`.`user` (
  `userID` INT(11) NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `admin` INT NULL,
  PRIMARY KEY (`userID`)
  );


-- -----------------------------------------------------
-- Table `foodpantry`.`basket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foodpantry`.`basket` ;

CREATE TABLE IF NOT EXISTS `foodpantry`.`basket` (
  `basketID` INT(11) NOT NULL,
  `basketDate` DATE NULL DEFAULT NULL,
  `userID` INT(11) NOT NULL,
  PRIMARY KEY (`basketID`),
  INDEX `fk_basket_user1_idx` (`userID` ASC),
  CONSTRAINT `fk_basket_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `foodpantry`.`user` (`userID`)
    );
   


-- -----------------------------------------------------
-- Table `foodpantry`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foodpantry`.`category` ;

CREATE TABLE IF NOT EXISTS `foodpantry`.`category` (
  `categoryID` INT(11) NOT NULL,
  `categoryType` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`categoryID`)
  );


-- -----------------------------------------------------
-- Table `foodpantry`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foodpantry`.`product` ;

CREATE TABLE IF NOT EXISTS `foodpantry`.`product` (
  `productID` INT(11) NOT NULL,
  `productName` VARCHAR(45) NULL DEFAULT NULL,
  `quantity` INT(11) NULL DEFAULT NULL,
  `categoryID` INT(11) NULL,
  `img` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`productID`),
  INDEX `product_ibfk_1_idx` (`categoryID` ASC),
  CONSTRAINT `product_ibfk_1`
    FOREIGN KEY (`categoryID`)
    REFERENCES `foodpantry`.`category` (`categoryID`)
    );


-- -----------------------------------------------------
-- Table `foodpantry`.`basketItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foodpantry`.`basketItem` ;

CREATE TABLE IF NOT EXISTS `foodpantry`.`basketItem` (
  `basketItemID` INT(11) NOT NULL,
  `productID` INT(11) NULL DEFAULT NULL,
  `basketID` INT(11) NULL DEFAULT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`basketItemID`),
  INDEX `productID` (`productID` ASC),
  INDEX `basketID` (`basketID` ASC),
  CONSTRAINT `BasketItem_ibfk_1`
    FOREIGN KEY (`productID`)
    REFERENCES `foodpantry`.`product` (`productID`),
  CONSTRAINT `BasketItem_ibfk_2`
    FOREIGN KEY (`basketID`)
    REFERENCES `foodpantry`.`basket` (`basketID`)
    );


-- -----------------------------------------------------
-- Table `foodpantry`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foodpantry`.`transactions` ;

CREATE TABLE IF NOT EXISTS `foodpantry`.`transactions` (
  `transactionID` INT NOT NULL,
  `date` DATE NULL,
  `userID` INT(11) NOT NULL,
  PRIMARY KEY (`transactionID`),
  INDEX `fk_transactions_user1_idx` (`userID` ASC),
  CONSTRAINT `fk_transactions_user1`
    FOREIGN KEY (`userID`)
    REFERENCES `foodpantry`.`user` (`userID`)
    );



-- -----------------------------------------------------
-- Table `foodpantry`.`transactionsDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `foodpantry`.`transactionsDetails` ;

CREATE TABLE IF NOT EXISTS `foodpantry`.`transactionsDetails` (
  `transactionID` INT NOT NULL,
  `id` INT NOT NULL,
  `quantity` INT NULL,
  `productID` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `productID_idx` (`productID` ASC),
  CONSTRAINT `productID`
    FOREIGN KEY (`productID`)
    REFERENCES `foodpantry`.`product` (`productID`),
  CONSTRAINT `transactionID`
    FOREIGN KEY (`transactionID`)
    REFERENCES `foodpantry`.`transactions` (`transactionID`)
    )